# Generated by Django 4.2.6 on 2023-12-03 18:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Designação')),
                ('code', models.CharField(blank=True, help_text='Introduza um código com 6 dígitos.', max_length=10, validators=[django.core.validators.RegexValidator(message='O código da Escola deve ter 6 dígitos.', regex='\\d{6}$')], verbose_name='Código')),
                ('slug', models.SlugField(blank=True, help_text='Deixar em branco para criar um slug automático e único', max_length=255, unique=True)),
                ('address', models.TextField(blank=True, verbose_name='Morada')),
                ('postal_code', models.CharField(blank=True, help_text='Insira um código postal com o formato "nnnn-nnn. Exemplo: 8100-128', max_length=12, validators=[django.core.validators.RegexValidator(message='Formato "nnnn-nnn". Exemplo: 8100-128', regex='^\\d{4}\\-\\d{3}$')], verbose_name='Código Postal')),
                ('locality', models.TextField(blank=True, verbose_name='Localidade')),
                ('phone1', models.CharField(blank=True, max_length=12, verbose_name='Telefone 1')),
                ('phone2', models.CharField(blank=True, max_length=12, verbose_name='Telefone 2')),
                ('nif', models.CharField(blank=True, default='600080781', help_text='Introduza um NIF com 9 dígitos', max_length=10, validators=[django.core.validators.RegexValidator(message=' O NIF deve conter 9 dígitos.', regex='\\d{9}$')], verbose_name='NIF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Modificado em')),
                ('diretor', models.CharField(blank=True, max_length=254, verbose_name='Diretor(a) do Agrupamento')),
                ('coordenador', models.CharField(blank=True, max_length=254, verbose_name='Coordenador(a) de estabelecimento')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Turma')),
                ('grade', models.CharField(choices=[('1ºANO', '1ºAno'), ('2ºANO', '2ºAno'), ('3ºANO', '3ºAno'), ('4ºANO', '4ºAno'), ('5ºANO', '5ºAno'), ('6ºANO', '6ºAno'), ('7ºANO', '7ºAno'), ('8ºANO', '8ºAno'), ('9ºANO', '9ºAno'), ('PRE', 'Pre-escola')], default='9ºAno', max_length=12, verbose_name='Nível')),
                ('slug', models.SlugField(blank=True, help_text='Deixar em branco para criar um slug automático e único.', max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.school', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Insira um ano letivo com o formato "aaaa/aaaa. Exemplo: 2022/2023', max_length=12, validators=[django.core.validators.RegexValidator(message='Formato "aaaa/aaaa. Exemplo: 2022/2023', regex='^\\d{4}\\/\\d{4}$')], verbose_name='Designação')),
                ('slug', models.SlugField(blank=True, help_text='Deixar em branco para criar um slug automático e único', max_length=20, unique=True)),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fim')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Ano Letivo',
                'verbose_name_plural': 'Anos Letivos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('short_name', models.CharField(max_length=20, verbose_name='Nome abreviado')),
                ('slug', models.SlugField(blank=True, help_text='Deixar em branco para criar um slug automático e único.', max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.schoolyear', verbose_name='Ano Letivo')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TeacherSchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Professores_turma', to='school_structure.schoolclass', verbose_name='Turma')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.schoolyear', verbose_name='Ano Letivo')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.subject', verbose_name='Disciplina')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Professores_turma', to='accounts.teacher', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Professor-Turma',
                'verbose_name_plural': 'Professores-turmas',
                'ordering': ('school_class',),
            },
        ),
        migrations.CreateModel(
            name='StudentSchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.IntegerField(verbose_name='Número de turma')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Alunos_turma', to='school_structure.schoolclass', verbose_name='Turma')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.schoolyear', verbose_name='Ano Letivo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Alunos_turma', to='accounts.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Aluno da Turma',
                'verbose_name_plural': 'Alunos da turma',
                'ordering': ('school_class',),
            },
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.schoolyear', verbose_name='Ano Letivo'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='students',
            field=models.ManyToManyField(related_name='students', through='school_structure.StudentSchoolClass', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='teachers',
            field=models.ManyToManyField(related_name='teachers', through='school_structure.TeacherSchoolClass', to='accounts.teacher'),
        ),
        migrations.CreateModel(
            name='CargoDT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Deixar em branco para criar um slug automático e único.', max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('school_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_structure.schoolclass', verbose_name='Turma')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.schoolyear', verbose_name='Ano Letivo')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Secretary', to='accounts.teacher', verbose_name='Secretário')),
                ('teacher_dt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CargosDT', to='accounts.teacher', verbose_name='Diretor de Turma')),
            ],
            options={
                'verbose_name': 'Cargo de DT',
                'verbose_name_plural': 'Cargos de DT',
                'ordering': ('teacher_dt',),
            },
        ),
    ]
