# Generated by Django 4.2.6 on 2023-12-31 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherschoolclass',
            options={'ordering': ('school_class',), 'verbose_name': 'Professor da Turma', 'verbose_name_plural': 'Professores da turma'},
        ),
    ]
