# Generated by Django 4.2.6 on 2024-02-18 21:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('type', models.CharField(choices=[('TEACHER', 'Professor'), ('STUDENT', 'Estudante'), ('EMPLOYEE', 'Funcionário')], default='TEACHER', max_length=50, verbose_name='Tipo')),
                ('name', models.CharField(max_length=254, verbose_name='Nome')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('sex', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=100, null=True, verbose_name='Sexo')),
                ('process_number', models.CharField(max_length=15, verbose_name='Número do processo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Telemóvel')),
                ('avatar', django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='users_fotos/no_image.png', force_format=None, keep_meta=True, quality=75, scale=None, size=[185, 185], upload_to='users_fotos/')),
                ('address', models.TextField(blank=True, verbose_name='Morada')),
                ('postal_code', models.CharField(blank=True, help_text='Insira um código postal com o formato "nnnn-nnn. Exemplo: 8100-128', max_length=12, validators=[django.core.validators.RegexValidator(message='Formato "nnnn-nnn". Exemplo: 8100-128', regex='^\\d{4}\\-\\d{3}$')], verbose_name='Código Postal')),
                ('locality', models.TextField(blank=True, verbose_name='Localidade')),
                ('nif', models.CharField(blank=True, help_text='Introduza um NIF com 9 dígitos', max_length=10, validators=[django.core.validators.RegexValidator(message=' O NIF deve conter 9 dígitos.', regex='\\d{9}$')], verbose_name='NIF')),
                ('nationality', models.CharField(blank=True, max_length=30, verbose_name='Nacionalidade')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Último acesso')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff')),
                ('is_active', models.BooleanField(default=False, verbose_name='Conta ativa')),
                ('is_superadmin', models.BooleanField(default=False, verbose_name='Super Administrador')),
                ('is_game', models.BooleanField(default=False, verbose_name='Membro GAME')),
                ('is_pias', models.BooleanField(default=False, verbose_name='administrador dos PIAS')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilizador',
                'verbose_name_plural': 'Todos os Utilizadores',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeMore',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(blank=True, max_length=150, verbose_name='Função')),
                ('workplace', models.CharField(blank=True, max_length=150, verbose_name='Local de Trabalho')),
            ],
            options={
                'verbose_name': 'Funcionário ++',
                'verbose_name_plural': 'Funcionários ++',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='StudentMore',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('father_name', models.CharField(blank=True, max_length=150, verbose_name='Nome do Pai')),
                ('father_phone', models.CharField(blank=True, max_length=12, verbose_name='Telemóvel do pai')),
                ('father_work', models.CharField(blank=True, max_length=60, verbose_name='Profissão do pai')),
                ('father_email', models.EmailField(blank=True, max_length=254, verbose_name='Email do pai')),
                ('mother_name', models.CharField(blank=True, max_length=150, verbose_name='Nome da mãe')),
                ('mother_phone', models.CharField(blank=True, max_length=12, verbose_name='Telemóvel da mãe')),
                ('mother_work', models.CharField(blank=True, max_length=60, verbose_name='Profissão da mãe')),
                ('mother_email', models.EmailField(blank=True, max_length=254, verbose_name='Email da mãe')),
                ('ee_kinship', models.CharField(blank=True, max_length=50, verbose_name='Parentesco')),
                ('ee_name', models.CharField(blank=True, max_length=150, verbose_name='Encarregado de Educação')),
                ('ee_phone', models.CharField(blank=True, max_length=12, verbose_name='Telemóvel do EE')),
                ('ee_work', models.CharField(blank=True, max_length=60, verbose_name='Profissão do EE')),
                ('ee_email', models.EmailField(blank=True, max_length=254, verbose_name='Email do EE')),
            ],
            options={
                'verbose_name': 'Aluno ++',
                'verbose_name_plural': 'Alunos ++',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ('name',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ('name',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ('name',),
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='TeacherMore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.CharField(max_length=200, verbose_name='Interesses')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
            options={
                'verbose_name': 'Prof ++',
                'verbose_name_plural': 'Profes ++',
                'ordering': ('user',),
            },
        ),
    ]
