# Generated by Django 4.2.6 on 2024-02-18 09:48

import apps.pias.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_structure', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiasType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Tipo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('slug', models.SlugField(blank=True, help_text='Deixar em branco para criar um slug automático e único', max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentSchoolRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=254, verbose_name='Agrupamento/Escola')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.schoolyear', verbose_name='Ano Letivo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percurso_aluno', to='accounts.student', verbose_name='Aluno')),
            ],
            options={
                'verbose_name': 'Percurso do Aluno',
                'verbose_name_plural': 'Percursos dos alunos',
                'ordering': ('school_year', 'created'),
            },
        ),
        migrations.CreateModel(
            name='PIAS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('doc_date', models.DateField(blank=True, null=True, verbose_name='Data do documento')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('slug', models.SlugField(blank=True, help_text='Deixar em branco para criar um slug automático e único', max_length=250, unique=True)),
                ('uploaded_to', models.FileField(max_length=500, upload_to=apps.pias.models.path_and_rename)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('related_docs', models.ManyToManyField(blank=True, to='pias.pias', verbose_name='Documentos relacionados')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_structure.schoolyear', verbose_name='Ano Letivo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student', verbose_name='Aluno')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pias.piastype', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'PIA',
                'verbose_name_plural': "PIA's",
                'ordering': ['name'],
            },
        ),
    ]
