# Generated by Django 4.2.6 on 2024-02-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pias',
            name='related_docs',
            field=models.ManyToManyField(blank=True, to='pias.pias', verbose_name='Documentos relacionados'),
        ),
    ]
