# Generated by Django 4.2.6 on 2024-02-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pias', '0002_alter_pias_related_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piastype',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
    ]
