# Generated by Django 4.2.6 on 2023-12-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pias', '0002_rename_desciption_pias_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piastype',
            old_name='desciption',
            new_name='description',
        ),
    ]
