# Generated by Django 4.2.6 on 2024-01-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pias', '0003_rename_desciption_piastype_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pias',
            options={'ordering': ['name'], 'verbose_name': 'PIA', 'verbose_name_plural': "PIA's"},
        ),
        migrations.AlterModelOptions(
            name='piastype',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documentos'},
        ),
    ]
